import { spawn } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import { Readable, PassThrough } from "node:stream";
import { gcStaleRuns, HEARTBEAT_STALE_MS } from "./pipeline-bootstrap.js";
import * as readline from "node:readline";
import type { Session } from "./session.js";
import { formatUserTurn } from "./stream-json-input.js";
import { parseStreamJsonEvents, type StreamJsonEvent } from "./stream-formatter.js";

export interface McpServerConfig {
  name: string;
  command: string;
  args: string[];
}

// Shorthand strings cover the common scalar types. Other JSON Schema types
// (array, object, integer, etc.) use the full object form: {type: "array", items: ...}.
export type JsonSchemaShorthand = "string" | "number" | "boolean";
export type JsonSchemaFragment =
  | JsonSchemaShorthand
  | { type?: string; enum?: unknown[]; [k: string]: unknown };

export type AgentModel = "opus" | "sonnet" | "haiku";
export type AgentThinking = "off" | "low" | "high";

interface DerivedJsonSchema {
  type: "object";
  properties: Record<string, { type?: string; enum?: unknown[]; [k: string]: unknown }>;
  required: string[];
  additionalProperties: false;
}

function deriveJsonSchemaString(outputs: Record<string, JsonSchemaFragment>): string {
  const properties: DerivedJsonSchema["properties"] = {};
  for (const [key, frag] of Object.entries(outputs)) {
    if (typeof frag === "string") {
      properties[key] = { type: frag };
    } else {
      properties[key] = frag as { type?: string; enum?: unknown[] };
    }
  }
  const schema: DerivedJsonSchema = {
    type: "object",
    properties,
    required: Object.keys(outputs),
    additionalProperties: false,
  };
  return JSON.stringify(schema);
}

export interface AgentConfig {
  name: string;
  description: string;
  model: AgentModel;
  thinking?: AgentThinking;
  permissionMode: string;
  tools: string[];
  mcp: McpServerConfig[];
  prompt: string;
  jsonSchema?: string;
  outputs?: Record<string, JsonSchemaFragment>;
  inputs?: string[];
  loop?: boolean;
  maxIterations?: number;
}

/**
 * Renderer-shaped projection of an AgentConfig. See `extractAgentMetadata`
 * in agent-loader.ts for the projection rules. Consumed by annotate-show.ts
 * for `apparat pipeline show` labels and available to any future
 * projection-shaped consumer (MCP introspection, scenario fixtures, JSON-mode
 * pipeline show) that wants a normalized label set without re-deriving it
 * from the AgentConfig field shape.
 *
 * `outputs` is the keys of AgentConfig.outputs Record — the renderer-visible
 * label set, not the JSON Schema fragments themselves.
 */
export interface AgentMetadata {
  inputs: string[];
  outputs: string[];
  model: AgentModel;
  thinking?: AgentThinking;
}

export interface RunOptions {
  cwd: string;
  signal?: AbortSignal;
  variables?: Record<string, unknown>;
  resume?: string;
  interactive?: boolean;
  onSessionId?: (id: string) => void;
  /** When provided, the caller consumes stdout (e.g. via streamEvents).
   *  The internal readline session-id extractor is skipped. */
  onStdout?: (stdout: NodeJS.ReadableStream) => Promise<void>;
  /** When provided, appended to the system prompt written to stdin. */
  message?: string;
  /** When provided, MCP-config and other run-scoped scratch files land in
   *  <cwd>/.apparat/runs/<runId>/ instead of <cwd>. Required for the
   *  heartbeat-driven GC introduced in ADR-0016. */
  runId?: string;
}

export interface ChildHandle {
  sessionId: string;
  events: AsyncGenerator<StreamJsonEvent>;
  submit: (text: string) => Promise<void>;
  end: () => Promise<void>;
  kill: (signal?: NodeJS.Signals) => Promise<void>;
  exited: Promise<{ code: number | null; signal: NodeJS.Signals | null; stderrTail: string }>;
}

export interface RunResult {
  exitCode: number;
  sessionId: string | null;
  stdout: import("stream").Readable | null;
  /** Buffered stdout content — populated when config.jsonSchema is set */
  output?: string;
}

const DEFAULTS: Partial<AgentConfig> = {
  permissionMode: "dangerouslySkipPermissions",
  tools: [],
  mcp: [],
};

/** Glob pattern matching MCP config files generated by writeMcpConfig() */
export const MCP_CONFIG_GLOB = ".mcp-*-*.json";

export class Agent {
  private _mcpConfigPath: string | null = null;

  constructor(public readonly config: AgentConfig) {}

  get mcpConfigPath(): string | null {
    return this._mcpConfigPath;
  }

  expandPrompt(variables?: Record<string, unknown>): string {
    if (!variables) return this.config.prompt;
    let result = this.config.prompt;
    for (const [key, value] of Object.entries(variables)) {
      const str = typeof value === "string" ? value : String(value ?? "");
      result = result.replace(new RegExp(`\\{\\{${key}\\}\\}`, "g"), str);
    }
    return result;
  }

  private buildCommonArgs(): string[] {
    const args: string[] = [];

    args.push("--model", this.config.model);

    if (this.config.permissionMode === "dangerouslySkipPermissions") {
      args.push("--dangerously-skip-permissions");
    } else {
      args.push("--permission-mode", this.config.permissionMode);
    }

    for (const tool of this.config.tools) {
      args.push("--allowedTools", tool);
    }

    if (this._mcpConfigPath) {
      args.push("--mcp-config", this._mcpConfigPath);
    }

    return args;
  }

  // Spawn env contract — design 2026-05-14 §3.2. Env-var spelling pinned against
  // Claude CLI 2.1.112 (Claude Code). Help excerpt: NO_MATCH: claude --help does
  // not mention thinking/budget/env.
  // If a future CLI version exposes a canonical thinking env var with a different
  // name, change the literal here in one place.
  private buildSpawnEnv(): NodeJS.ProcessEnv {
    if (this.config.thinking && this.config.thinking !== "off") {
      return { ...process.env, CLAUDE_THINKING_BUDGET: this.config.thinking };
    }
    return process.env;
  }

  buildArgs(options: RunOptions): string[] {
    const args = this.buildCommonArgs();

    // Output format (non-interactive only).
    // When jsonSchema is set, schema is embedded in the prompt by agent-handler.ts;
    // we use stream-json so text deltas reach the TUI in real-time.
    if (!options.interactive) {
      args.push("--output-format", "stream-json", "--verbose");
    }

    // Resume or prompt
    if (options.resume) {
      args.push("--resume", options.resume);
    }

    return args;
  }

  writeMcpConfig(opts: { cwd: string; runId?: string; variables?: Record<string, unknown> }): string | null {
    if (this.config.mcp.length === 0) return null;

    const { cwd, runId, variables } = opts;
    const expand = (s: string): string => {
      if (!variables) return s;
      return s.replace(/\{\{(\w+)\}\}/g, (match, key) => {
        const v = variables[key];
        if (v === undefined) return match;
        return typeof v === "string" ? v : String(v);
      });
    };

    const mcpServers: Record<string, { command: string; args: string[] }> = {};
    for (const server of this.config.mcp) {
      mcpServers[server.name] = {
        command: expand(server.command),
        args: server.args.map(expand),
      };
    }

    const targetDir = runId
      ? path.join(cwd, ".apparat", "runs", runId)
      : cwd;
    fs.mkdirSync(targetDir, { recursive: true });
    const configPath = path.join(targetDir, `.mcp-${this.config.name}-${Date.now()}.json`);
    fs.writeFileSync(configPath, JSON.stringify({ mcpServers }, null, 2));
    this._mcpConfigPath = configPath;
    return configPath;
  }

  cleanupMcpConfig(): void {
    if (this._mcpConfigPath) {
      try {
        fs.unlinkSync(this._mcpConfigPath);
      } catch {
        // File may already be removed
      }
      this._mcpConfigPath = null;
    }
  }

  async run(options: RunOptions): Promise<RunResult> {
    const expandedPrompt = this.expandPrompt(options.variables);

    // Sweep stale run folders before writing any new scratch (ADR-0016).
    const swept = gcStaleRuns(options.cwd);
    if (swept > 0) {
      const minutes = Math.round(HEARTBEAT_STALE_MS / 60_000);
      process.stderr.write(
        `[apparat] swept ${swept} stale run folder(s) (no heartbeat for ≥ ${minutes} min)\n`,
      );
    }

    // Write MCP config if needed (expand variables in server args)
    this.writeMcpConfig({ cwd: options.cwd, runId: options.runId, variables: options.variables });

    try {
      const args = this.buildArgs(options);
      const isInteractive = !!options.interactive;
      const isResume = !!options.resume;

      // Add -p for non-interactive runs (resume or fresh — corrective message
      // goes via stdin in both cases)
      if (!isInteractive) {
        args.unshift("-p");
      }

      const spawnOptions: any = {
        cwd: options.cwd,
        detached: true,
        env: this.buildSpawnEnv(),
      };

      if (isInteractive) {
        spawnOptions.stdio = "inherit";
      } else {
        spawnOptions.stdio = ["pipe", "pipe", "inherit"];
      }

      const child = spawn("claude", args, spawnOptions);

      // Kill child immediately when the caller aborts (e.g. Ctrl+C).
      // The child is spawned with detached:true so it won't receive the
      // terminal's SIGINT — we must kill it explicitly.
      let onAbort: (() => void) | undefined;
      if (options.signal) {
        onAbort = () => {
          child.kill("SIGTERM");
          const escalation = setTimeout(() => {
            if (!child.killed) child.kill("SIGKILL");
          }, 3000);
          child.once("close", () => clearTimeout(escalation));
        };
        if (options.signal.aborted) {
          onAbort();
        } else {
          options.signal.addEventListener("abort", onAbort, { once: true });
        }
      }

      // Pipe content for non-interactive runs.
      // Resume: only the new user-turn (system prompt already in the resumed session).
      // Fresh: full system prompt, optionally followed by an initial message.
      if (!isInteractive && child.stdin) {
        const stdinContent = isResume
          ? (options.message ?? "")
          : (options.message
              ? `${expandedPrompt}\n\n${options.message}`
              : expandedPrompt);
        child.stdin.write(stdinContent);
        child.stdin.end();
      }

      // Capture session ID from stream-json output
      let sessionId: string | null = null;

      // Register close handler BEFORE consuming stdout to avoid race condition:
      // if onStdout awaits stream consumption and close fires before we listen, we'd hang.
      const closePromise = new Promise<number>((resolve) => {
        child.on("close", (code) => {
          options.signal?.removeEventListener("abort", onAbort!);
          resolve(code ?? 1);
        });
      });

      let capturedOutput = "";

      if (this.config.jsonSchema && !isInteractive && child.stdout) {
        // Tee stdout: forward all NDJSON lines to onStdout (for TUI streaming)
        // while accumulating into capturedOutput (for agent-handler JSON extraction).
        // readline drains child.stdout; passThrough.end() is called on readline close,
        // so awaiting onStdout implicitly waits for the full stream.
        const passThrough = new PassThrough();
        passThrough.on("error", () => { /* consumer error; readline still drains */ });
        const rl = readline.createInterface({ input: child.stdout });

        rl.on("line", (line) => {
          capturedOutput += line + "\n";
          passThrough.push(line + "\n");
          try {
            const parsed = JSON.parse(line) as Record<string, unknown>;
            if (typeof parsed.session_id === "string" && !sessionId) {
              sessionId = parsed.session_id;
              options.onSessionId?.(sessionId);
            }
          } catch { /* not JSON */ }
        });
        rl.on("close", () => passThrough.end());

        if (options.onStdout) {
          await options.onStdout(passThrough);
        } else {
          // Drain passThrough so readline can finish and capturedOutput is complete.
          await new Promise<void>((resolve) => {
            passThrough.resume();
            passThrough.once("end", resolve);
          });
        }
      } else if (!isInteractive && child.stdout && options.onStdout) {
        // Caller consumes stdout (e.g. streamEvents → output.stream)
        await options.onStdout(child.stdout);
      } else if (!isInteractive && child.stdout) {
        const rl = readline.createInterface({ input: child.stdout });
        rl.on("line", (line) => {
          try {
            const parsed = JSON.parse(line);
            if (parsed.session_id && !sessionId) {
              sessionId = parsed.session_id;
              options.onSessionId?.(sessionId!);
            }
          } catch {
            // Not JSON, ignore
          }
        });
      }

      const exitCode = await closePromise;

      return {
        exitCode,
        sessionId,
        stdout: (isInteractive || this.config.jsonSchema) ? null : (child.stdout as Readable | null),
        output: capturedOutput || undefined,
      };
    } finally {
      this.cleanupMcpConfig();
    }
  }

  buildInteractiveArgs(opts: { systemPrompt: string; sessionId: string }): string[] {
    const args = ["-p", ...this.buildCommonArgs()];

    // Stream-json bidirectional protocol
    args.push("--input-format", "stream-json");
    args.push("--output-format", "stream-json");
    args.push("--verbose");

    // System prompt appended (not replacing CLI's default)
    args.push("--append-system-prompt", opts.systemPrompt);

    // Session continuity
    args.push("--session-id", opts.sessionId);

    return args;
  }

  runInteractive(opts: {
    session: Session;
    systemPrompt: string;
    cwd: string;
    variables?: Record<string, unknown>;
  }): ChildHandle {
    this.writeMcpConfig({ cwd: opts.cwd, variables: opts.variables });

    const args = this.buildInteractiveArgs({
      systemPrompt: opts.systemPrompt,
      sessionId: opts.session.id,
    });

    const child = spawn("claude", args, {
      cwd: opts.cwd,
      stdio: ["pipe", "pipe", "pipe"],
      env: this.buildSpawnEnv(),
    });

    // Capture stderr into a rolling tail so crashes are visible to the UI.
    // Without this, errors like "Claude Code cannot be launched inside another
    // Claude Code session" would be swallowed silently under the Ink render.
    const STDERR_TAIL_MAX = 4096;
    let stderrTail = "";
    child.stderr?.on("data", (chunk: Buffer) => {
      stderrTail += chunk.toString("utf8");
      if (stderrTail.length > STDERR_TAIL_MAX) {
        stderrTail = stderrTail.slice(-STDERR_TAIL_MAX);
      }
    });

    let ended = false;

    type ExitInfo = { code: number | null; signal: NodeJS.Signals | null; stderrTail: string };
    let exitResult: ExitInfo | null = null;
    let resolveExited: (r: ExitInfo) => void;
    const exitedPromise = new Promise<ExitInfo>((res) => {
      resolveExited = res;
    });

    const closePromise = new Promise<number>((resolve) => {
      child.on("close", (code, signal) => {
        ended = true;
        this.cleanupMcpConfig();
        exitResult = { code: code ?? null, signal: signal ?? null, stderrTail };
        resolveExited!(exitResult);
        resolve(code ?? 1);
      });
    });

    const events = parseStreamJsonEvents(child.stdout!);

    const submit = async (text: string): Promise<void> => {
      if (ended || !child.stdin || child.stdin.destroyed) {
        throw new Error("Child process stdin is closed or not writable");
      }
      const line = formatUserTurn(text);
      return new Promise<void>((resolve, reject) => {
        child.stdin!.write(line, (err) => {
          if (err) reject(err);
          else resolve();
        });
      });
    };

    const end = async (): Promise<void> => {
      if (!ended && child.stdin && !child.stdin.destroyed) {
        child.stdin.end();
      }
      await closePromise;
    };

    const killFn = async (signal: NodeJS.Signals = "SIGTERM"): Promise<void> => {
      child.kill(signal);
      const escalationTimeout = setTimeout(() => {
        if (!ended) child.kill("SIGKILL");
      }, 3000);
      await closePromise;
      clearTimeout(escalationTimeout);
    };

    return {
      sessionId: opts.session.id,
      events,
      submit,
      end,
      kill: killFn,
      exited: exitedPromise,
    };
  }

}

export function validateAgentConfig(
  config: Partial<AgentConfig> & { prompt?: string; auto_inputs?: boolean },
): AgentConfig {
  if (!config.name) throw new Error("name is required");
  if (!config.description) throw new Error("description is required");
  // Empty string is valid (procedure-less agents like `task`); only missing field is invalid.
  if (typeof config.prompt !== "string") throw new Error("prompt body is required");

  if (config.model !== "opus" && config.model !== "sonnet" && config.model !== "haiku") {
    throw new Error(
      `model is required and must be one of opus|sonnet|haiku (got: ${config.model ?? "undefined"})`
    );
  }
  if (config.thinking !== undefined &&
      config.thinking !== "off" &&
      config.thinking !== "low" &&
      config.thinking !== "high") {
    throw new Error(
      `thinking must be one of off|low|high (got: ${config.thinking})`
    );
  }

  if (config.loop !== undefined && typeof config.loop !== "boolean") {
    throw new Error("loop must be a boolean");
  }
  if (config.maxIterations !== undefined &&
      (typeof config.maxIterations !== "number" ||
       !Number.isInteger(config.maxIterations) ||
       config.maxIterations < 0)) {
    throw new Error("maxIterations must be a non-negative integer");
  }

  // Derive jsonSchema from outputs only when at least one output key is
  // declared and jsonSchema is not explicitly provided. Empty `outputs: {}`
  // means "no structured output" — used by interactive agents that stream
  // chat instead of producing JSON.
  const hasDeclaredOutputs = !!config.outputs && Object.keys(config.outputs).length > 0;
  const derivedJsonSchema = (hasDeclaredOutputs && !config.jsonSchema)
    ? deriveJsonSchemaString(config.outputs!)
    : config.jsonSchema;

  return {
    name: config.name,
    description: config.description,
    model: config.model,
    permissionMode: config.permissionMode ?? DEFAULTS.permissionMode!,
    tools: config.tools ?? DEFAULTS.tools!,
    mcp: config.mcp ?? DEFAULTS.mcp!,
    prompt: config.prompt,
    ...(derivedJsonSchema !== undefined ? { jsonSchema: derivedJsonSchema } : {}),
    ...(config.outputs !== undefined ? { outputs: config.outputs } : {}),
    ...(config.inputs !== undefined ? { inputs: config.inputs } : {}),
    ...(config.thinking !== undefined ? { thinking: config.thinking } : {}),
    ...(config.loop !== undefined ? { loop: config.loop } : {}),
    ...(config.maxIterations !== undefined ? { maxIterations: config.maxIterations } : {}),
  };
}
